/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/floppy.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/floppy.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-2.782, 0.186, 2.658]} scale={0.01}>
        <mesh geometry={nodes.Box_LP.geometry} material={materials['floppy.001']} />
        <mesh geometry={nodes.Circle_LP.geometry} material={materials['floppy.002']} />
        <mesh geometry={nodes.Main_LP.geometry} material={materials.floppy} />
        <mesh geometry={nodes.Metal_LP.geometry} material={materials['floppy.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/floppy.glb')
